apiVersion: v1
kind: ConfigMap
metadata:
  name: frpc-config
data:
  frpc.toml: |
    log.level = "trace"
    auth.token = "{{ .Envs.FRP_SERVER_TOKEN }}"

    serverAddr = "{{ .Envs.FRP_SERVER_ENDPOINT }}"
    serverPort = 443
    transport.protocol = "wss"

    [[proxies]]
    name = "conferenceli"
    type = "http"
    localPort = 8000
    subdomain = "conferenceli"
