apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  labels:
    app.kubernetes.io/name: contactform
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  storageClassName: local-path
