apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: generic-device-plugin
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: apps
  source:
    path: deployment/apps/generic-device-plugin
    repoURL: https://github.com/vshn/conferenceli.git
    targetRevision: HEAD
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
