apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: podLister
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: podListers
subjects:
  - kind: ServiceAccount
    name: default
roleRef:
  kind: Role
  name: podLister
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: podstatus
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: podstatus
subjects:
  - kind: ServiceAccount
    name: default
    namespace: podstatus
roleRef:
  kind: Role
  name: podstatus
  apiGroup: rbac.authorization.k8s.io
