apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: podstalk
spec:
  selector:
    matchLabels:
      app: podstalk
  serviceName: podstalk
  replicas: 3
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: podstalk
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: podstalk
          image: docker.io/mhutter/podstalk
          ports:
            - containerPort: 8080
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_SA
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
