apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: critical-prod
spec:
  selector:
    matchLabels:
      app: critical-prod
  serviceName: critical-prod
  replicas: 5
  template:
    metadata:
      labels:
        app: critical-prod
    spec:
      terminationGracePeriodSeconds: 1
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - pc0
                      - pc1
                      - pc2
            - weight: 1
              preference:
                matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: NotIn
                    values:
                      - conferenceli
      tolerations:
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 30
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 30
      containers:
        - name: echo
          image: ghcr.io/vshn/conferenceli-demopod:main
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: CPU_PATTERN
              value: random
            - name: CPU_INTENSITY
              value: "0.8"
