apiVersion: apps/v1
kind: Deployment
metadata:
  name: blinkstick
  labels:
    app.kubernetes.io/name: blinkstick
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: blinkstick
  template:
    metadata:
      labels:
        app.kubernetes.io/name: blinkstick
    spec:
      serviceAccountName: default
      containers:
        - name: blinkstick
          image: ghcr.io/vshn/conferenceli-podstatus:main
          imagePullPolicy: Always
          command:
            - python
            - conferenceli/blinkstick-controller.py
          env:
            - name: LOG_LEVEL
              value: INFO
            - name: K8S_NAMESPACE
              value: http-echo
          envFrom:
            - secretRef:
                name: podstatus-env
          resources:
            limits:
              squat.ai/blinkstick: "1"
