apiVersion: apps/v1
kind: Deployment
metadata:
  name: podstatus
  labels:
    app.kubernetes.io/name: podstatus
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: podstatus
  template:
    metadata:
      labels:
        app.kubernetes.io/name: podstatus
    spec:
      serviceAccountName: default
      nodeSelector:
        kubernetes.io/hostname: conferenceli
      containers:
        - name: podstatus
          image: ghcr.io/vshn/conferenceli-podstatus:main
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: LOG_LEVEL
              value: INFO
            - name: K8S_NAMESPACE
              value: http-echo
          envFrom:
            - secretRef:
                name: podstatus-env
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources: {}
