apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "podstatus:node-reader"
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "podstatus:node-reader"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "podstatus:node-reader"
subjects:
  - kind: ServiceAccount
    name: default
    namespace: podstatus
