apiVersion: v1
kind: ConfigMap
metadata:
  name: frpc-config
data:
  frpc.toml: |
    log.level = "trace"
    auth.token = "{{ .Envs.FRP_SERVER_TOKEN }}"

    serverAddr = "{{ .Envs.FRP_SERVER_ENDPOINT }}"
    serverPort = 443
    transport.protocol = "wss"

    [[proxies]]
    name = "conferenceli"
    type = "http"
    localIP = "contactform.contactform"
    localPort = 8080
    subdomain = "conferenceli"

    [[proxies]]
    name = "podstatus"
    type = "http"
    localIP = "podstatus.podstatus"
    localPort = 8080
    subdomain = "podstatus"

    [[proxies]]
    name = "kubernetes"
    type = "tcp"
    localIP = "kubernetes.default.svc"
    localPort = 443
    remotePort = 6102
